Add example of theme change
FilledStacks/expression-ui pull request #12
Opened 2024-04-20 10:55 UTC by rafaelovandov

**Description**
Inspired by responsive builder pr, I thought of idea of how to have themes in the app without code anything for colors, etc.

**Demo**
https://github.com/FilledStacks/expression-ui/assets/66031839/f7e5e27b-cef2-48a0-ad11-71d0c5659a56

2024-04-20 11:37 UTC, rafaelovandov commented
I think the best approach to using theme and responsive together is to check if the artboard name contains light or dark and mobile, tablet, or desktop

2024-04-25 17:49 UTC, FilledStacks submitted a review, later dismissed
Ooooooooooh nice. 

I like this idea 💡 Very awesome, thank you @rafaelovandov

2024-04-25 17:52 UTC, FilledStacks requested changes
Awesome work, I really like the idea 💡

I appreciate you taking the effort to make this PR.

2024-04-25 17:52 UTC, FilledStacks commented on examples/example-flutter/lib/ui/views/startup/startup_view.dart
> +            MediaQuery.of(context).platformBrightness == Brightness.light
This removes the Startup view intro. 

Can you please instead create a new view called themeView and add these changes in there. 

I'll link them all together in the next update of the example app.

2024-04-25 17:52 UTC, FilledStacks commented on examples/example-flutter/lib/constants/expression_constants.dart
> +const String ksExpressionUIFilePath = 'assets/app.riv';
Please add a new value instead for your new .riv file

2024-04-26 13:38 UTC, rafaelovandov commented
I created the new theme view, you need only to update the artboard names and add new views in your riv. 
Do you have a Discord server or something to communicate faster than this? This idea is pretty cool. I have some questions.

2024-05-17 13:14 UTC, FilledStacks commented
@rafaelovandov yes I do, I just got back from paternity leave. 

Here's a link to the discord. https://discord.gg/FbaVQPPc

2024-05-17 13:15 UTC, FilledStacks approved these changes

2024-05-17 13:15 UTC, merged